import './global.css';
import { UsersProvider } from '@financeapp/users-frontend';

export const metadata = {
  title: 'Welcome to webclient',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <UsersProvider>
      <html lang="en">
        <body>{children}</body>
      </html>
    </UsersProvider>
  );
}
