import './global.css';
import { ReactNode } from 'react';
import { UsersProvider } from '@financeapp/users-frontend';
import { SidebarProvider, SidebarTrigger, SidebarInset, Separator } from '@financeapp/shadcn-ui';
import { AppSidebar } from '@/components/sidebar';
import { cookies } from 'next/headers';

export const metadata = {
  title: 'Welcome to webclient',
  description: 'Generated by create-nx-workspace',
};

export default async function RootLayout({ children }: { children: ReactNode }) {
  const cookieStore = await cookies();
  const openSidebar = cookieStore.get('sidebar_state')?.value === 'true';

  return (
    <UsersProvider>
      <html lang="en">
        <body>
          <SidebarProvider defaultOpen={openSidebar}>
            <AppSidebar />
            <SidebarInset>
              {/* Header */}
              <header className="flex h-16 shrink-0 items-center gap-2 border-b">
                <div className="flex items-center gap-2 px-3">
                  <SidebarTrigger />
                  <Separator orientation="vertical" className="mr-2 h-4" />
                  TODO: TITLE
                </div>
              </header>
              {/*  Content*/}
              <main>{children}</main>
            </SidebarInset>
          </SidebarProvider>
        </body>
      </html>
    </UsersProvider>
  );
}
