version: '3.5'

services:
  message-queue:
    container_name: rabbitmq
    image: rabbitmq:3.6-management
    hostname: rabbitmq

    ports:
      - 15672:15672
      - 5672:5672

    healthcheck:
      test: rabbitmq-diganostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

    env_file:
      - ./environments/rabbitMQ.env

  user-worker:
    container_name: user-worker1
    image: ghcr.io/towech-financeapp/userservice:latest
    
    depends_on:
      - "message-queue"

    volumes:
      - ./logs/UserService:/usr/app/logs

    networks:
      - main-network

    env_file:
      - ./environments/UserService.env

  transaction-worker:
    container_name: transaction-worker1
    image: ghcr.io/towech-financeapp/transactionservice:latest

    depends_on:
      - "message-queue"

    volumes:
      - ./logs/TransactionService:/usr/app/logs

    networks:
      - main-network

    env_file:
      - ./environments/TransactionService.env

  category-worker:
    container_name: category-worker1
    image: ghcr.io/towech-financeapp/cateogryreportservice:latest

    depends_on:
      - "message-queue"

    volumes:
      - ./logs/CategoryReportService:/usr/app/logs

    networks:
      - main-network

    env_file:
      - ./environments/CategoryReportService.env

  web-api:
    container_name: web-api1
    image: ghcr.io/towech-financeapp/webapi:latest

    depends_on:
      - "message-queue"

    volumes:
      - ./logs/WebApi:/usr/app/logs

    env_file:
      - ./environments/WebAPI.env

    ports:
      - "3001:3000"

  web-client:
    container_name: webClient

    build:
      context: ./WebClient
      target: prod
      args:
        REACT_APP_WEBAPI: http://192.168.0.135:3001

    networks:
      - main-network

    ports:
      - 3000:3000

networks:
  main-network:
    driver: bridge