version: '3.5'

services:

  message-queue:
    container_name: rabbitmq
    image: rabbitmq:3.6-management
    hostname: rabbitmq

    ports:
      - 15672:15672
      - 5672:5672

    networks:
      - main-network

    healthcheck:
      test: rabbitmqctl node_health_check
      interval: 30s
      timeout: 30s
      retries: 3

    env_file:
      - ./environments/rabbitMQ.env

  transaction-worker:
    container_name: transaction-worker1
    image: ghcr.io/towech-financeapp/transactionservice:1.10.1

    depends_on:
      message-queue:
        condition: service_healthy

    volumes:
      - ./logs/TransactionService:/usr/app/logs

    networks:
      - main-network

    env_file:
      - ./environments/TransactionService.env

  category-worker:
    container_name: category-worker1
    image: ghcr.io/towech-financeapp/cateogryreportservice:1.2.2

    depends_on:
      message-queue:
        condition: service_healthy

    volumes:
      - ./logs/CategoryReportService:/usr/app/logs

    networks:
      - main-network

    env_file:
      - ./environments/CategoryReportService.env

  web-api:
    container_name: web-api1
    image: ghcr.io/towech-financeapp/webapi:1.4.1

    depends_on:
      message-queue:
        condition: service_healthy

    networks:
      - main-network

    volumes:
      - ./logs/WebApi:/usr/app/logs

    env_file:
      - ./environments/WebAPI.env

    ports:
      - '3001:3000'

  web-client:
    container_name: web-client1

    build:
      context: ../../financeapp-legacy/WebClient
      target: prod

    networks:
      - main-network

    ports:
      - 3000:80

networks:
  main-network:
